#! /bin/sh
set -x

MACPORTS_ACLOCAL=/opt/local/share/aclocal

ACLOCAL_OPTS=
if test -d /opt/local/share/aclocal; then
	ACLOCAL_OPTS="${ACLOCAL_OPTS} -I ${MACPORTS_ACLOCAL}"
fi

aclocal ${ACLOCAL_OPTS}

LIBTOOLIZE=`which libtoolize 2> /dev/null`
GLIBTOOLIZE=`which glibtoolize 2> /dev/null`

# if test -x "${LIBTOOLIZE}"; then
#   libtoolize --force --copy
# elif test -x "${GLIBTOOLIZE}"; then
#   glibtoolize --force --copy
# else
#   echo "Can\'t find libtoolize"
#   exit 1
# fi

if grep AM_CONFIG_HEADER configure.ac > /dev/null 2> /dev/null; then
  autoheader
fi
automake --add-missing --copy
autoconf

cat configure.ac | grep AC_CONFIG_SUBDIRS | sed s'/AC_CONFIG_SUBDIRS(\(.*\))/\1/' |
while read subdir; do
(
  cd ${subdir}
  ./bootstrap
)
done
